### ISSUE TITLE
Rarely happening errors (report to aiohttp maintainers?)

### ISSUE THREAD

**Issue by achimnol** [lablup/sorna-manager#23]
Though it seems not to affect the service, I could see this on the production log:
```
2017-01-10 05:45:22 ERROR aiohttp.server Error handling request
Traceback (most recent call last):
  File "/home/sorna/venv/lib/python3.6/site-packages/aiohttp/server.py", line 268, in start
    self.transport.write_eof()
  File "/home/sorna/.pyenv/versions/3.6.0/lib/python3.6/asyncio/transports.py", line 117, in write_eof
    raise NotImplementedError
NotImplementedError
```

**Comment by achimnol** [comment]
Reported as KeepSafe/aiohttp#1537.

**Comment by achimnol** [comment]
Another case: (this might/might not be a bug in aiohttp)
```
2017-01-18 02:53:52 ERROR asyncio Fatal error on transport TCPTransport (error status in uv_stream_t.read callback)
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f2b48c6ac18>
transport: <TCPTransport closed=False reading=False 0x250e498>
TimeoutError: [Errno 110] Connection timed out
2017-01-18 02:53:52 WARNING aiohttp.parsers StreamParser set_exception TimeoutError(110, 'Connection timed out')
```

**Comment by achimnol** [comment]
Now fixed in the latest version, and aiohttp v2 is going to be stabilized. Closing this.
